
spring:
  datasource:
    hikari:
      # DataBase Settings : hikariCP : https://github.com/brettwooldridge/HikariCP
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ssafytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
      username: ssafy
      password: ssafy
      pool-name: hikari-pool

      # hikariCP property setting
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  # JSP Path (ViewResolver)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#MyBatis Setting
mybatis:
  type-aliases-package: com.jeogi.jeogitrip.*.model
  mapper-locations: /mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


server:
  port: '80'

#log level Setting
logging:
  level:
    com:
    ssafy: debug
  root: info

jwt:
  secret: ${jwt.secret-key}